/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lesah_000_ndkclipservice_ClipServiceDaemon */

#ifndef _Included_com_example_lesah_000_ndkclipservice_ClipServiceDaemon
#define _Included_com_example_lesah_000_ndkclipservice_ClipServiceDaemon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lesah_000_ndkclipservice_ClipServiceDaemon
 * Method:    takeMesgJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_lesah_1000_ndkclipservice_ClipServiceDaemon_takeMesgJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lesah_000_ndkclipservice_ClipServiceDaemon
 * Method:    dataAvailableJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_lesah_1000_ndkclipservice_ClipServiceDaemon_dataAvailableJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lesah_000_ndkclipservice_ClipServiceDaemon
 * Method:    dataSendMesgToHostJNI
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_lesah_1000_ndkclipservice_ClipServiceDaemon_dataSendMesgToHostJNI
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
