/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lesah_000_ndkclipservice_AutoStart */

#ifndef _Included_com_example_lesah_000_ndkclipservice_AutoStart
#define _Included_com_example_lesah_000_ndkclipservice_AutoStart
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lesah_000_ndkclipservice_AutoStart
 * Method:    dataAvailableJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_lesah_1000_ndkclipservice_AutoStart_dataAvailableJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
