/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lesah_000_ndkclipservice_AutoStart_ClipboardListener */

#ifndef _Included_com_example_lesah_000_ndkclipservice_AutoStart_ClipboardListener
#define _Included_com_example_lesah_000_ndkclipservice_AutoStart_ClipboardListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
